### PR TITLE
More generic buffer types to support autodiff

### PR DESCRIPTION
**Pull request by vvpisarev**
For #10

This should not change the existing behavior with plain numeric types, only enable computing chemical potentials and their derivatives via e.g. `jacobian(n -> log_c_activity(mix, n, ...), nmol)`.

### CODE REVIEW

**Comment by vvpisarev** [comment]
Do not merge yet, branch is WIP

**Comment by vvpisarev** [comment]
So far, automatic differentiation by mole numbers and volume seems to work and agree with analytical functions.
Autodiff by temperature errors.

**Comment by stepanzh** [comment]
The PR is closed for future, as I need to rebase dev.

**Comment by stepanzh** [comment]
After rebasing PR has conflicts, seems like its easier to make a new autodiff branch and manually duplicate the changes.

**Pull request closed without merging**
